name: menu
description: Flutter Menu App.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  responsive_grid_list: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: lib/assets/fonts/Tajawal-Bold.ttf
        - asset: lib/assets/fonts/Tajawal-Light.ttf
        - asset: lib/assets/fonts/Tajawal-Medium.ttf
        - asset: lib/assets/fonts/Tajawal-Regular.ttf
      
